Moved limine and and ilar to extlibs, USEILAR argument, README.md update

diff --git a/extlibs/Makefile b/extlibs/Makefile
--- a/extlibs/Makefile
+++ b/extlibs/Makefile
@@ -1,11 +1,18 @@
 LIBDIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
 ROOTDIR := $(shell dirname $(LIBDIR))
 
-all: $(LIBDIR)/lai $(LIBDIR)/cwalk $(LIBDIR)/printf $(LIBDIR)/limine.h $(LIBDIR)/cxxshim $(LIBDIR)/scalable-font2
+all: $(LIBDIR)/lai $(LIBDIR)/ilar $(LIBDIR)/cwalk $(LIBDIR)/printf $(LIBDIR)/limine $(LIBDIR)/cxxshim $(LIBDIR)/scalable-font2
 
 $(LIBDIR)/lai:
 	echo "Downloading lai"
 	git clone --single-branch --branch=master --depth=1 https://github.com/thomtl/lai || echo "\e[31mFailed to download lai!\e[0m"
+
+$(LIBDIR)/ilar:
+ifdef USEILAR
+	@echo "Downloading ilar"
+	@git clone --single-branch --branch=master --depth=1 https://github.com/ilobilo/ilar || echo "\e[31mFailed to download ilar!\e[0m"
+	$(MAKE) -sC $(LIBDIR)/ilar
+endif
 
 $(LIBDIR)/cwalk:
 	echo "Downloading cwalk"
@@ -15,9 +22,10 @@ $(LIBDIR)/printf:
 	echo "Downloading printf"
 	git clone --single-branch --branch=master --depth=1 https://github.com/eyalroz/printf || echo "\e[31mFailed to download printf!\e[0m"
 
-$(LIBDIR)/limine.h:
-	echo "Downloading limine.h"
-	wget -nc https://raw.githubusercontent.com/limine-bootloader/limine/trunk/limine.h || echo "\e[31mFailed to download limine.h!\e[0m"
+$(LIBDIR)/limine:
+	@echo "Downloading limine"
+	@git clone --single-branch --branch=v3.0-branch-binary --depth=1 https://github.com/limine-bootloader/limine || echo "\e[31mFailed to download limine!\e[0m"
+	$(MAKE) -sC $(LIBDIR)/limine
 
 $(LIBDIR)/cxxshim:
 	echo "Downloading cxxshim"
@@ -28,4 +36,4 @@ $(LIBDIR)/scalable-font2:
 	git clone --single-branch --branch=master --depth=1 https://gitlab.com/bztsrc/scalable-font2 || echo "\e[31mFailed to download ssfn!\e[0m"
 
 clean:
-	rm -rf $(LIBDIR)/lai $(LIBDIR)/cwalk $(LIBDIR)/printf $(LIBDIR)/limine.h $(LIBDIR)/cxxshim $(LIBDIR)/scalable-font2
+	rm -rf $(LIBDIR)/lai $(LIBDIR)/ilar $(LIBDIR)/cwalk $(LIBDIR)/printf $(LIBDIR)/limine $(LIBDIR)/cxxshim $(LIBDIR)/scalable-font2
