changes

diff --git a/extlibs/Makefile b/extlibs/Makefile
--- a/extlibs/Makefile
+++ b/extlibs/Makefile
@@ -1,39 +1,39 @@
-LIBDIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
-ROOTDIR := $(shell dirname $(LIBDIR))
+EXTLIBDIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
+ROOTDIR := $(shell dirname $(EXTLIBDIR))
 
-all: $(LIBDIR)/lai $(LIBDIR)/ilar $(LIBDIR)/cwalk $(LIBDIR)/printf $(LIBDIR)/limine $(LIBDIR)/cxxshim $(LIBDIR)/scalable-font2
+all: $(EXTLIBDIR)/lai $(EXTLIBDIR)/ilar $(EXTLIBDIR)/cwalk $(EXTLIBDIR)/printf $(EXTLIBDIR)/limine $(EXTLIBDIR)/cxxshim $(EXTLIBDIR)/scalable-font2
 
-$(LIBDIR)/lai:
+$(EXTLIBDIR)/lai:
 	echo "Downloading lai"
-	git clone --single-branch --branch=master --depth=1 https://github.com/thomtl/lai || echo "\e[31mFailed to download lai!\e[0m"
+	git clone --single-branch --branch=master --depth=1 https://github.com/managarm/lai || echo "\e[31mFailed to download lai!\e[0m"
 
-$(LIBDIR)/ilar:
+$(EXTLIBDIR)/ilar:
 ifdef USEILAR
 	@echo "Downloading ilar"
 	@git clone --single-branch --branch=master --depth=1 https://github.com/ilobilo/ilar || echo "\e[31mFailed to download ilar!\e[0m"
-	$(MAKE) -sC $(LIBDIR)/ilar
+	$(MAKE) -sC $(EXTLIBDIR)/ilar
 endif
 
-$(LIBDIR)/cwalk:
+$(EXTLIBDIR)/cwalk:
 	echo "Downloading cwalk"
 	git clone --single-branch --branch=master --depth=1 https://github.com/likle/cwalk || echo "\e[31mFailed to download cwalk!\e[0m"
 
-$(LIBDIR)/printf:
+$(EXTLIBDIR)/printf:
 	echo "Downloading printf"
 	git clone --single-branch --branch=master --depth=1 https://github.com/eyalroz/printf || echo "\e[31mFailed to download printf!\e[0m"
 
-$(LIBDIR)/limine:
+$(EXTLIBDIR)/limine:
 	@echo "Downloading limine"
 	@git clone --single-branch --branch=v3.0-branch-binary --depth=1 https://github.com/limine-bootloader/limine || echo "\e[31mFailed to download limine!\e[0m"
-	$(MAKE) -sC $(LIBDIR)/limine
+	$(MAKE) -sC $(EXTLIBDIR)/limine
 
-$(LIBDIR)/cxxshim:
+$(EXTLIBDIR)/cxxshim:
 	echo "Downloading cxxshim"
 	git clone --single-branch --branch=master --depth=1 https://github.com/managarm/cxxshim || echo "\e[31mFailed to download cxxshim!\e[0m"
 
-$(LIBDIR)/scalable-font2:
+$(EXTLIBDIR)/scalable-font2:
 	echo "Downloading scalable-font2"
 	git clone --single-branch --branch=master --depth=1 https://gitlab.com/bztsrc/scalable-font2 || echo "\e[31mFailed to download ssfn!\e[0m"
 
 clean:
-	rm -rf $(LIBDIR)/lai $(LIBDIR)/ilar $(LIBDIR)/cwalk $(LIBDIR)/printf $(LIBDIR)/limine $(LIBDIR)/cxxshim $(LIBDIR)/scalable-font2
+	rm -rf $(EXTLIBDIR)/lai $(EXTLIBDIR)/ilar $(EXTLIBDIR)/cwalk $(EXTLIBDIR)/printf $(EXTLIBDIR)/limine $(EXTLIBDIR)/cxxshim $(EXTLIBDIR)/scalable-font2
