Makefile updates

diff --git a/source/Makefile b/source/Makefile
--- a/source/Makefile
+++ b/source/Makefile
@@ -1,15 +1,26 @@
-KERNEL := kernel.bin
 SOURCEDIR := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
 BACKGROUND := $(SOURCEDIR)/bg.bmp
 INITRD := $(SOURCEDIR)/initrd.tar.gz
+KERNEL := $(SOURCEDIR)/kernel.bin
+ISO := $(SOURCEDIR)/../image.iso
+
+LIMINE = $(SOURCEDIR)/../limine/limine-install
+XORRISO = xorriso
+QEMU = qemu-system-x86_64
+
+QEMUFLAGS =  -enable-kvm -cpu max -smp 12 -m 512M -rtc base=localtime -serial stdio
+XORRISOFLAGS = -as mkisofs -b limine-cd.bin \
+		-no-emul-boot -boot-load-size 4 -boot-info-table \
+		--efi-boot limine-eltorito-efi.bin -efi-boot-part \
+		--efi-boot-image --protective-msdos-label
 
 CC = x86_64-pc-elf-gcc
 CPP = x86_64-pc-elf-g++
 LD = x86_64-pc-elf-ld
 AS = nasm
 
-CFLAGS = -O3 -pipe
-CPPFLAGS = -O3 -pipe
+CFLAGS = -O3 -pipe -w
+CPPFLAGS = -O3 -pipe -w
 LDFLAGS = 
 ASMFLAGS = 
 
@@ -62,6 +73,7 @@ all: $(KERNEL) initrd iso clean run
 bios: $(KERNEL) initrd iso clean run-bios
 
 $(KERNEL): $(OBJ)
+	echo "Building kernel..."
 	$(LD) $(LDFLAGS) $(INTERNALLDFLAGS) $(OBJ) -o $@
 
 %.o: %.c
@@ -74,25 +86,26 @@ $(KERNEL): $(OBJ)
 	$(AS) $(ASMFLAGS) $^ -f elf64 -o $@
 
 initrd:
-	@tar czf $(INITRD) -C $(SOURCEDIR)/initramfs/ ./
+	echo "\nCreating initrd..."
+	tar czf $(INITRD) -C $(SOURCEDIR)/initramfs/ ./
 
 iso:
 	cp $(KERNEL) $(BACKGROUND) $(INITRD) $(SOURCEDIR)/../limine.cfg $(SOURCEDIR)/../limine/limine.sys \
 		$(SOURCEDIR)/../limine/limine-cd.bin $(SOURCEDIR)/../limine/limine-eltorito-efi.bin $(SOURCEDIR)/../iso_root/
 
-	xorriso -as mkisofs -b limine-cd.bin \
-		-no-emul-boot -boot-load-size 4 -boot-info-table \
-		--efi-boot limine-eltorito-efi.bin \
-		-efi-boot-part --efi-boot-image --protective-msdos-label \
-		$(SOURCEDIR)/../iso_root -o $(SOURCEDIR)/../image.iso > /dev/null
-
-	$(SOURCEDIR)/../limine/limine-install $(SOURCEDIR)/../image.iso > /dev/null
+	echo "\nBuilding iso image..."
+	$(XORRISO) $(XORRISOFLAGS) $(SOURCEDIR)/../iso_root -o $(ISO) 2> /dev/null || echo "\e[31mFailed to build iso!\e[0m"
+		
+	echo "\nInstaling limine..."
+	$(LIMINE) $(ISO) 2> /dev/null || echo "\e[31mFailed to install limine!\e[0m"
 
 clean:
 	rm -rf $(KERNEL) $(OBJ) $(INITRD) $(SOURCEDIR)/../iso_root/*
 
 run:
-	qemu-system-x86_64 -enable-kvm -cpu max -smp 12 -m 512M -rtc base=localtime -serial stdio -cdrom $(SOURCEDIR)/../image.iso -drive if=pflash,format=raw,unit=0,file=$(SOURCEDIR)/../ovmf/OVMF_CODE-pure-efi.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=$(SOURCEDIR)/../ovmf/OVMF_VARS-pure-efi.fd
+	echo "\nBooting iso in uefi mode..."
+	$(QEMU) $(QEMUFLAGS) -cdrom $(ISO) -drive if=pflash,format=raw,unit=0,file=$(SOURCEDIR)/../ovmf/OVMF_CODE-pure-efi.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=$(SOURCEDIR)/../ovmf/OVMF_VARS-pure-efi.fd 2> /dev/null
 
 run-bios:
-	qemu-system-x86_64 -enable-kvm -cpu max -smp 12 -m 512M -rtc base=localtime -serial stdio -cdrom $(SOURCEDIR)/../image.iso -boot d
+	echo "\nBooting iso in bios mode..."
+	$(QEMU) $(QEMUFLAGS) -cdrom $(ISO) 2> /dev/null
